# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PlsReadme < Formula
  desc "Pls Readme! This allows you to create a README.md file for your projects!"
  homepage "https://github.com/homepage"
  version "1.2.8"
  license "MIT"

  depends_on "git"
  depends_on "go"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kush-daga/readme-generator-cli/releases/download/v1.2.8/pls-readme_1.2.8_macOS_arm64.tar.gz"
      sha256 "a1356380eb2d01d6c401e8593d14a12ca575e8ce1c518fe019c9f21b6658ae84"

      def install
        bin.install "pls-readme"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kush-daga/readme-generator-cli/releases/download/v1.2.8/pls-readme_1.2.8_macOS_x86_64.tar.gz"
      sha256 "ea68ae9997cbf53c928f3f35d4cdc68af8934c0d9aae34bba57ffc7e8c12dff0"

      def install
        bin.install "pls-readme"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kush-daga/readme-generator-cli/releases/download/v1.2.8/pls-readme_1.2.8_Linux_x86_64.tar.gz"
      sha256 "30f5b9c3c8411a9ba16711c1a75344535a84945908a3b4feff9cd1f14dcea7da"

      def install
        bin.install "pls-readme"
      end
    end
  end
end
